[workspace]
resolver = "3"
members = ["bfs_order_traversal","bns_first_true","bns_vanila", "dfs_max_depth", "ht_vanila", "linkedlist", "playground"]

[workspace.dependencies]
paris = {version = "1.5", features=["macros","timestamps"]}
